### ISSUE TITLE
你们线上在用吗?

### ISSUE THREAD

**Issue by w3hacker** [vipshop/hiredis-vip#1]
hiredis什么意见

**Comment by deep011** [comment]
Yes, we are using it in product.

**Comment by w3hacker** [comment]
我改用这个了 https://github.com/twitter/twemproxy

**Comment by deep011** [comment]
Yeah, twemproxy is also good for redis, any question contact with me.

**Comment by w3hacker** [comment]
codis 太复杂了 虽然我学过go 但是还是不想用那东西 wandoujia维护的

**Comment by deep011** [comment]
we also do not used codis, redis cluster is the future directoin.

**Comment by w3hacker** [comment]
@deep011 如果redis单点失效 那不是数据都获取不到了

**Comment by deep011** [comment]
You used twemproxy+redis or redis cluster?
