### ISSUE TITLE
Warnings during make

### ISSUE THREAD

**Issue by LazyHippogriff** [vipshop/hiredis-vip#108]
I am getting the following warnings when I run make.

dict.c:160: warning: âdictReplaceâ defined but not used
dict.c:182: warning: âdictDeleteâ defined but not used
hircluster.c:1495: warning: âcluster_update_route_with_nodes_oldâ defined but not used
hircluster.c:1953: warning: âprint_cluster_node_listâ defined but not used
hircluster.c:2515: warning: ânode_get_by_slotâ defined but not used
hircluster.c:2651: warning: âslot_get_by_commandâ defined but not used

How can I remove these warnings, so that I can use these functions in my program?

**Comment by thakurajayL** [comment]
Isn't it ok to have some APIs defined but not used ? It should not harm you by any chance.

**Comment by LazyHippogriff** [comment]
Actually I wanted to try using these APIs in my application.

**Comment by thakurajayL** [comment]
I dont think these are public APIs. You are not suppose to use these api's from application.
