### ISSUE TITLE
执行redisClusterGetReply收到MOVED语句以及redisClusterCommand没有断线重连机制

### ISSUE THREAD

**Issue by dennisip86** [vipshop/hiredis-vip#11]
你好:
    1. redisClusterCommand没有断线重连机制,而redisClusterAppendCommand有.
    2. 在测试主从切换后执行redisClusterGetReply,收到MOVED语句,以下是测试过程:

* 测试代码: 
```
while(true) {

        // reply = (redisReply *)redisClusterCommand(cluster_ctx, "GET a");
        // if (!reply) {
        //     printf("Execute fail.\n");
        // } else {
        //     printf("%s\n", reply->str);
        //     freeReplyObject(reply);
        // }
        //
        // reply = (redisReply *)redisClusterCommand(cluster_ctx, "GET b");
        // if (!reply) {
        //     printf("Execute fail.\n");
        // } else {
        //     printf("%s\n", reply->str);
        //     freeReplyObject(reply);
        // }
        //
        // reply = (redisReply *)redisClusterCommand(cluster_ctx, "GET c");
        // if (!reply) {
        //     printf("Execute fail.\n");
        // } else {
        //     printf("%s\n", reply->str);
        //     freeReplyObject(reply);
        // }
        //
        // printf("Done\n");
        // getchar();
        // continue;

        int rc;
        rc = redisClusterAppendCommand(cluster_ctx, "GET a");
        if (REDIS_OK != rc) {
            printf("Append fail.[%s]\n", cluster_ctx->errstr);
        }

        rc = redisClusterAppendCommand(cluster_ctx, "GET b");
        if (REDIS_OK != rc) {
            printf("Append fail.[%s]\n", cluster_ctx->errstr);
        }

        rc = redisClusterAppendCommand(cluster_ctx, "GET c");
        if (REDIS_OK != rc) {
            printf("Append fail.[%s]\n", cluster_ctx->errstr);
        }

        reply = NULL;
        rc = redisClusterGetReply(cluster_ctx, (void **)&reply);
        if (REDIS_OK != rc || !reply) {
            printf("Get reply fail.\n");
        } else {
            printf("%s\n", reply->str);
        }
        if (reply) {
            freeReplyObject(reply);
        }

        reply = NULL;
        rc = redisClusterGetReply(cluster_ctx, (void **)&reply);
        if (REDIS_OK != rc || !reply) {
            printf("Get reply fail.\n");
        } else {
            printf("%s\n", reply->str);
        }
        if (reply) {
            freeReplyObject(reply);
        }

        reply = NULL;
        rc = redisClusterGetReply(cluster_ctx, (void **)&reply);
        if (REDIS_OK != rc || !reply) {
            printf("Get reply fail.\n");
        } else {
            printf("%s\n", reply->str);
        }
        if (reply) {
            freeReplyObject(reply);
        }

        printf("Done\n");
        getchar();
    }
```

1. 执行程序连接redis并正确获得GET a,b,c的内容
1. 所有从库执行cluster failover接替主库
1. 输入回车再次获取,收到MOVED语句

**Comment by deep011** [comment]
你好！
1. redisClusterCommand是可以自动更新路由表的，需要在slave编程master后，路由表会自动更新。
2. cluster的pipeline在一个patch执行完后，一定要执行redisCLusterReset()函数。详情请看readme里关于pipeline的使用说明。

**Comment by dennisip86** [comment]
你好,
1. redisClusterCommand没有断线重连机制的意思应该时,当redis服务重启后,若使用pipelining形式再次调用接口,第一次reply为NULL,而第二次会自动恢复,使用redisClusterCommand则调用多少次都不会恢复.测试用例时上述注释的那段.
1.  测试用例确实忘了执行redisCLusterReset(),我在printf("Done\n");前添加了redisCLusterReset(cluster_ctx);但是主从切换后的第一次查询.还是返回了MOVED语句,第二次查询恢复.

**Comment by deep011** [comment]
1. 你下载的是master的代码？还是release里的代码？
2. 在一个patch中如果slot信息发生变化，pipeline不做错误处理，也不做重试动作，只在redisCLusterReset中更新路由。现在暂时只能做成这样。

**Comment by dennisip86** [comment]
我的代码是commit: 699a702febb7dfd4e616c1987ece92ebc7dee840
假如slot信息发生变化,pipeline向调用的接口返回MODED指令,,按道理应该是有hiredis-vip去处理这个MOVED的指令再返回结果而不应该直接返回到调用者吧.

**Comment by deep011** [comment]
1. 你下载master的最新代码试试redisClusterCommand()。你是把master进程kill了吗？
2. 按道理是该hiredis-vip去处理，但这样会导致pipeline很慢，直接返回错误会很快。在目前这种情况下，建议把出错的命令再新城一个新的pipeline去执行。两个pipeline之间要执行redisCLusterReset。

**Comment by dennisip86** [comment]
1. 我下载了master的代码重新测试redisClusterCommand,结果还是一样.没有断线重连,redisClusterCommand测试我是逐个把master kill掉测试的.而pipeline的测试是在从库执行cluster failover直接切换到主库,与hiredis-vip的连接没有断开的.
2. 每次redisCLusterReset是否都会重刷路由表,这样是否比处理moved更慢?

**Comment by deep011** [comment]
1. 逐个把master kill？你的集群cluster-require-full-coverage配置设置的是什么？
2. redisCLusterReset函数会判断是否需要更新路由，集群稳定时是不需要刷新路由的，所以什么都不干。集群不稳定的时候，redisCLusterReset函数会刷新一次路由，这是很快的。如果在一个patch中，hiredis-vip去处理了所有的moved错误，这才会很慢。

**Comment by dennisip86** [comment]
cluster-require-full-coverage为默认的yes
逐个的意思是,kill掉master后等待从库接替主库后再kill下一个.kill完所有的master后,redis集群状态还是健康的.

**Comment by deep011** [comment]
redis集群编程健康的以后，redisClusterCommand函数还是返回错误？

**Comment by dennisip86** [comment]
是的.

**Comment by deep011** [comment]
返回的是什么错误？

**Comment by dennisip86** [comment]
```
Execute fail.
Execute fail.
Execute fail.
Done

Execute fail.
Execute fail.
Execute fail.
Done

Execute fail.
Execute fail.
Execute fail.
Done

Execute fail.
Execute fail.
Execute fail.
Done
```

reply为NULL

**Comment by deep011** [comment]
你把cc->errstr打印出来：
if (cc->err) {
    printf("cc->errstr: %s\n", cc->errstr);
}

**Comment by deep011** [comment]
我大概知道为什么了，你在建立cluster_ctx的时候加上HIRCLUSTER_FLAG_ADD_SLAVE属性：
cluster_ctx = redisClusterConnect("ip:port",HIRCLUSTER_FLAG_ADD_SLAVE);

**Comment by dennisip86** [comment]
问题解决.感谢你的回答:)

**Comment by deep011** [comment]
怎么解决的？

**Comment by dennisip86** [comment]
连接的时候加上HIRCLUSTER_FLAG_ADD_SLAVE

**Comment by deep011** [comment]
不加HIRCLUSTER_FLAG_ADD_SLAVE的话cluster_ctx->errstr里是什么？

**Comment by dennisip86** [comment]
no reachable node in cluster
