### ISSUE TITLE
SET command not work when I use NonBlock connection

### ISSUE THREAD

**Issue by istvan-yang** [vipshop/hiredis-vip#13]
redisContext *c = redisConnectNonBlock(hostname,port);
redisReply *reply = redisCommand(c,"set %d %d",1,2);
printf("set: %s\n",reply->str);

these code raise a segmentation fault，reply is a NULL pointer

**Comment by deep011** [comment]
Why you want to use redisConnectNonBlock() function?
This function always used for asynchronous.

**Comment by istvan-yang** [comment]
I just want to test whether it can accelerate the processing or not, could you show me a demo or pieces of codes that use redisClusterConnectNonBlock() to connect the server and then set some data into redis?

**Comment by deep011** [comment]
please see : https://github.com/vipshop/hiredis-vip/blob/master/examples/example-libevent.c
