### ISSUE TITLE
请教一下批量操作问题

### ISSUE THREAD

**Issue by wciq1208** [vipshop/hiredis-vip#15]
1.在使用libevent作为异步框架时进行mget操作没触发回调函数，请问怎么解决？
2.没有针对异步模式的pipeline么？

**Comment by deep011** [comment]
1. 异步操作不支持多key(mget/mset等)操作。
2. 连续多次调用redisClusterAsyncCommand()函数，就相当于用了pipeline了。

**Comment by wciq1208** [comment]
连续多次调用redisClusterAsyncCommand使得客户端跟服务端频繁的在系统调用栈和网络栈上切换不是反而让效率降低了么

**Comment by deep011** [comment]
这个函数只是把要发送的命令格式化后加入了发送缓冲区了，不涉及系统调用。真正的发送动作是在后面。

**Comment by MarinYoung4596** [comment]
使用redisAppendCommand批量添加query，但是读取过程中连接断开了。这时候如果重连，redisAppendCommand里暂存的命令还有么？
