### ISSUE TITLE
master/slave

### ISSUE THREAD

**Issue by usergoodvery** [vipshop/hiredis-vip#2]
Hi,
I was wondering if this library automatically recognises failover between master and slave nodes for a clustered node? Documentation doesn't seem to cover that.

regards,

**Comment by deep011** [comment]
Don't worry. Hiredis-vip is able to keep consistent state with redis cluster both cluster synchronous API and cluster asynchronous API.

**Comment by usergoodvery** [comment]
Thanks for your reply. Just to confirm: if let's say a cluster has 3 members and each member has 1 slave each. If a slave is promoted to master for a given slot, your implementation will automatically update the ip/port for that slot to be the slave's?

**Comment by deep011** [comment]
Yes, it can update the ip and port.
Hiredis-vip handled the moved/ask errors, and when moved error happend, the ip/port will be updated.
All those actions is apparent to user.
