### ISSUE TITLE
hi，关于mget命令的问题。 slot[0,10]分配在一个master上，有10个key对应的slot刚好是0-10，此时mget是向这一个master发送了10个mget命令请求吗？

### ISSUE THREAD

**Issue by xian-zx** [vipshop/hiredis-vip#20]
hi，slot [0,10] 都分配在一个master上，有10个key需要查询，这10个key对应的slot刚好是0-10，此时执行mget命令，hiredis-vip会创建10个sub_command，执行10次mget。这种情况，当前hiredis-vip能否支持只发送一次mget命令？ 谢谢

**Comment by deep011** [comment]
![image](https://cloud.githubusercontent.com/assets/10265268/19339292/29803f16-9155-11e6-82e8-394a096ce720.png)

mget中的key好像不能跨slot

**Comment by xian-zx** [comment]
确实如此，谢谢

**Comment by dennisip86** [comment]
注意提示,是same slot不是same node.
mget {b}1 {b}2
这种方式强制key存放在同一个slot中,可以使用mget访问多个key的

**Comment by deep011** [comment]
@dennisip86  我们说的就是slot。不管这些key分布在哪里，hiredis-vip都可以使用mget/mset操作的，没必要使用前缀。

**Comment by dennisip86** [comment]
我理解错了
官方文档推荐多key操作的命令使用hash tag.

**Comment by deep011** [comment]
使用hash tag客户端开发是有代价的，并且也只能针对一小部分key，所以并不具备普遍性。

**Comment by dennisip86** [comment]
hash tag也属于官方标准.而hiredis-vip的mget支持跨slot访问是非标准的.反而不具备兼容性,假如项目内使用跨语言访问redis,会造成其他语言使用有障碍.

**Comment by deep011** [comment]
其他客户端只要实现了mget/mset操作，是一样的使用，用户不需要关心内部实现，只不过有效率高低之分。hash tag的使用让开发略伤神。。。

**Comment by dennisip86** [comment]
CROSSSLOT: Keys in request don't hash to the same slot
我用nodejs的thunk-redis测试了一个mget a b.得到这个错误
而mget {b}a {b}b则正常

**Comment by deep011** [comment]
那就是thunk-redis不支持跨slot的mget，换个试试
