### ISSUE TITLE
reply is null[route update error, please recreate redisClusterContext!]

### ISSUE THREAD

**Issue by mahb94** [vipshop/hiredis-vip#21]
复制的例子代码,返回标题的错误,是什么情况呢
`
redisClusterContext *cc = redisClusterConnect("172.18.33.6:7000,172.18.33.6:7001,172.18.33.6:7002", HIRCLUSTER_FLAG_NULL);
    if(cc == NULL || cc->err)
    {
        printf("connect error : %s\n", cc == NULL ? "NULL" : cc->errstr);
        return -1;
    }

    redisReply *reply = (redisReply*)redisClusterCommand(cc, "get  %s", "tttt");
    if(reply == NULL)
    {
        printf("reply is null[%s]\n", cc->errstr);
        redisClusterFree(cc);
        return -1;
    }
`

**Comment by deep011** [comment]
你看下172.18.33.6:7000,172.18.33.6:7001,172.18.33.6:7002这三个节点是不是都连不上了？

**Comment by mahb94** [comment]
我的集群命令不对原来是,把127.0.0.1写成具体地址就可以了,不好意思
src/redis-trib.rb create --replicas 1 172.18.33.6:7000 172.18.33.6:7001 172.18.33.6:7002 172.18.33.6:7003 172.18.33.6:7004 172.18.33.6:7005
