### ISSUE TITLE
redisClusterGetReply获取的reply为NULL

### ISSUE THREAD

**Issue by xielm12** [vipshop/hiredis-vip#24]
通过pipeline发送命令后，采用redisClusterGetReply获取结果时错误。c->errstr结果为：Server closed the connection。redisClusterGetReply内部是有重连的，为什么还会出现这个问题呢？ 另外， redisCLusterReset函数中调用redisClusterGetReply的话貌似会阻塞！

**Comment by deep011** [comment]
"MOVED"
"ASK"
"TRYAGAIN"
"CROSSSLOT"
"CLUSTERDOWN"
只有上述5中错误，hiredis-vip才会重试。

redisClusterGetReply()和redisCLusterReset()函数主要是给pipeline用的，当然是阻塞的。如果你要非阻塞，请用异步API。

**Comment by xielm12** [comment]
可能我的表达有问题，是redisClusterGetReply获取结果时只要出现Server closed the connection，就会假死。

**Comment by deep011** [comment]
你Cluster前有用proxy吗？

**Comment by xielm12** [comment]
没有代理

**Comment by deep011** [comment]
config get *timeout*
config get *client*
你在你任何一个master上执行这个命令，把结果贴出来

**Comment by xielm12** [comment]
10.172.170.136:16993> config get timeout
1) "timeout"
2) "30"
10.172.170.136:16993> config get client
(empty list or set)
10.172.170.136:16993>

**Comment by deep011** [comment]
你们的timeout为啥设置的30秒？

**Comment by xielm12** [comment]
redis 集群是其他部门部署的。是timeout的问题？

**Comment by deep011** [comment]
应该是，设置的太小了，设置成300秒

**Comment by xielm12** [comment]
好像不是timeout的设置问题，现在设置为300秒了，问题还在。单实例的redis从来没碰见过这样的问题。

**Comment by deep011** [comment]
pipeline里有没有什么特别的命令？你尝试把pipeline拆分成单条命令，看看是执行哪个命令出错的？

**Comment by deep011** [comment]
另外，你把info all命令的结果贴出来

**Comment by xielm12** [comment]
pipeline全都是Get命令。单独用Get命令一条一条的执行正常。
info all：
# Server
redis_version:3.2.0
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:f131395545d36412
redis_mode:cluster
os:Linux 2.6.32-220.7.1.el6.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.4.6
process_id:25831
run_id:0e2452f6a5421a3ecfb6aed1d6fc6d3c544e51ca
tcp_port:16993
uptime_in_seconds:2429170
uptime_in_days:28
hz:10
lru_clock:3336636
executable:/usr/local/redis32/bin/redis-server
config_file:/data1/redis16993/redis16993.conf

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:1075420368
used_memory_human:1.00G
used_memory_rss:1813647360
used_memory_rss_human:1.69G
used_memory_peak:1782859352
used_memory_peak_human:1.66G
total_system_memory:169121726464
total_system_memory_human:157.51G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:21000000000
maxmemory_human:19.56G
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.69
mem_allocator:jemalloc-4.0.3

# Persistence
loading:0
rdb_changes_since_last_save:70949995
rdb_bgsave_in_progress:0
rdb_last_save_time:1477302483
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:1753481
total_commands_processed:2668800654
instantaneous_ops_per_sec:0
total_net_input_bytes:143461344585
total_net_output_bytes:1426350920125
instantaneous_input_kbps:0.03
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:1
sync_partial_ok:0
sync_partial_err:0
expired_keys:2
evicted_keys:0
keyspace_hits:2585564771
keyspace_misses:12202844
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:825
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:1
slave0:ip=10.172.170.82,port=16993,state=online,offset=5892575368,lag=1
master_repl_offset:5892575368
repl_backlog_active:1
repl_backlog_size:1073741824
repl_backlog_first_byte_offset:4818833545
repl_backlog_histlen:1073741824

# CPU
used_cpu_sys:3359.75
used_cpu_user:11895.47
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_get:calls=2224908852,usec=2844298028,usec_per_call=1.28
cmdstat_set:calls=13844842,usec=78865739,usec_per_call=5.70
cmdstat_setnx:calls=1197150,usec=4515215,usec_per_call=3.77
cmdstat_setex:calls=1953729,usec=13213486,usec_per_call=6.76
cmdstat_mget:calls=349921221,usec=558779440,usec_per_call=1.60
cmdstat_sadd:calls=5826329,usec=24940802,usec_per_call=4.28
cmdstat_smembers:calls=4,usec=76,usec_per_call=19.00
cmdstat_zadd:calls=28473112,usec=148331568,usec_per_call=5.21
cmdstat_zremrangebyscore:calls=18757967,usec=41983407,usec_per_call=2.24
cmdstat_zrange:calls=20207195,usec=4120816593,usec_per_call=203.93
cmdstat_zrangebyscore:calls=5,usec=47,usec_per_call=9.40
cmdstat_select:calls=1,usec=2,usec_per_call=2.00
cmdstat_expire:calls=1236698,usec=1389588,usec_per_call=1.12
cmdstat_auth:calls=9,usec=9,usec_per_call=1.00
cmdstat_ping:calls=20254,usec=16090,usec_per_call=0.79
cmdstat_psync:calls=1,usec=1630,usec_per_call=1630.00
cmdstat_replconf:calls=2410253,usec=2044078,usec_per_call=0.85
cmdstat_flushdb:calls=10,usec=5659610,usec_per_call=565961.00
cmdstat_flushall:calls=236,usec=39448302,usec_per_call=167153.83
cmdstat_info:calls=20419,usec=1382307,usec_per_call=67.70
cmdstat_ttl:calls=3,usec=9,usec_per_call=3.00
cmdstat_config:calls=20263,usec=275481,usec_per_call=13.60
cmdstat_cluster:calls=2099,usec=422383,usec_per_call=201.23
cmdstat_slowlog:calls=2,usec=38,usec_per_call=19.00

# Cluster
cluster_enabled:1

# Keyspace

**Comment by xielm12** [comment]
当pipeline出现“Server closed the connection”这个错误时， redisCLusterReset 函数内部会调用redisClusterGetReply去继续从socket里边读数据，可是服务端把连接断掉了，所以造成了程序假死。我采用重连策略， 就解决问题了。

**Comment by deep011** [comment]
关键为什么有“Server closed the connection”这个错误，很明显是redis主动关闭的连接，什么原因呢？你的pipeline里存在quit命令吗？

**Comment by xielm12** [comment]
我也找到了Server closed the connection的重现方式：就是你昨天提到的timeout的问题，客户端静默300s之后再执行pipeline，就必定会出现Server closed the connection错误。

**Comment by deep011** [comment]
那肯定啊，redis的timeout配置项就是用来杀掉空闲连接的。

**Comment by deep011** [comment]
你把你相关的代码贴出来我看下

**Comment by deep011** [comment]
这个redis设置timeout后，pipeline阻塞的问题，我修复了下，你可以试试。
使用方法是：redisClusterGetReply()返回错误后就不要继续调用redisClusterGetReply()函数了，需执行redisCLusterReset()来修复来重新执行一个新的pipeline。
