### ISSUE TITLE
是不是不支持 KEYS 命令？

### ISSUE THREAD

**Issue by helloBingGeGe** [vipshop/hiredis-vip#27]
```
QS ERR 2016-12-23 11:24:05.239 30257 30257 cluster_client.cpp:56:check_redis_reply: exec cmd=[KEYS a*] reply is null
QS DBG 2016-12-23 11:24:05.239 30257 30257 cluster_client.cpp:72:check_redis_reply: cmd=[del a#2],type=[3:REDIS_REPLY_INTEGER],integer=[1],len=[0],str = [(null)],elements=[0]
```
KEYS a* 匹配不到结果， 但其实是有的， 有个使用场景是想删除指定模式的 key 需要 keys 命令匹配所有的 key 然后全部删除，可以支持吗大哥？或者有别的变通方法吗？求指教，谢谢！

**Comment by deep011** [comment]
用redis-cluster-tool
![image](https://cloud.githubusercontent.com/assets/10265268/21446685/47f9315a-c904-11e6-8a08-6f80e7f254cb.png)

**Comment by helloBingGeGe** [comment]
额， 这个功能不能加到 hiredis-vip 里面吗， 我想在应用程序里面在特点时间做这件事情

**Comment by deep011** [comment]
这个可能需要你自己支持了，redis-cluster-tool也是用hiredis-vip实现的。
可以用hircluster.h中的cluster_node结构体，其中的con和acon是节点相关的连接。

**Comment by helloBingGeGe** [comment]
好我看看 redis-cluster-tool 的实现，O(∩_∩)O谢谢
