### ISSUE TITLE
incr命令不支持吗？  example.c例子运行incr未起效

### ISSUE THREAD

**Issue by kanghaibo** [vipshop/hiredis-vip#29]
运行examples/example.c，INCR未起效
`[root@localhost_ hiredis-vip-master]# ./examples/hiredis-example 
PING: PONG
SET: MOVED 12182 192.168.119.136:7002
SET (binary API): OK
GET foo: MOVED 12182 192.168.119.136:7002
INCR counter: 0
INCR counter: 0
0) element-9
1) element-8
2) element-7
3) element-6
4) element-5
5) element-4
6) element-3
7) element-2
8) element-1
9) element-0
`

**Comment by deep011** [comment]
请查看这里的例子：https://github.com/vipshop/hiredis-vip/wiki
