### ISSUE TITLE
Add redisClustervCommand

### ISSUE THREAD

**Issue by dennisip86** [vipshop/hiredis-vip#3]
Hi, 
I'm going to create a c++ wrapper.Would you like to add APIs like redisvCommand in hiredis then I could pass the va_list.
thanks.

**Comment by deep011** [comment]
HI, 
I'm so sorry just to see your question.
I just updated the cluster api, and add three functions:
redisClustervCommand()
redisClustervAppendCommand()
redisClustervAsyncCommand()

Try it.

**Comment by dennisip86** [comment]
Thank you very much.
