### ISSUE TITLE
不支持连接出错后，自动切换到下一个地址进行重连

### ISSUE THREAD

**Issue by justme9527** [vipshop/hiredis-vip#31]
集群模式下，不支持连接出错后，自动切换到下一个地址进行重连

**Comment by deep011** [comment]
连接出错的问题已经有处理的，详细描述下你的问题

**Comment by justme9527** [comment]
redisClusterConnect("192.168.137.4:7004,192.168.137.6:7006",
                                           HIRCLUSTER_FLAG_ROUTE_USE_SLOTS);
当7004连接出错后，不能自动换到7006上去？

**Comment by deep011** [comment]
报什么错呢？在你的集群里执行 cluster nodes命令我看看。

**Comment by justme9527** [comment]
不好意思，redisClusterConnect API没有问题，是自己测试还不够仔细，自己的连接池写的有问题，
手动kill掉7004，出错信息为error number:3 error msg: Server closed the connection，
过一段时间后用同样的地址还是可以建立连接，然后请问下error number是在哪里定义的，比方说上面提到的错误码3
