### ISSUE TITLE
请教一个redis-cluster的问题

### ISSUE THREAD

**Issue by zzs625005** [vipshop/hiredis-vip#38]
你好，我想请教一个问题。我部署了一台6主6从的redis-cluster（版本3.0.7），在调用c++客户端执行get操作不断加压时，发现有1个节点的cpu利用率飙到了100%，而剩下的11个节点cpu利用率不到10%。对redis-cluster的读取操作不是均衡分布的吗？我想请教下这个是不是和redis-cluster的运行机制有关系啊？还是和我们的client设计有关系？（ps：get操作的key是int64的，value是30-40k的字符串）。谢谢！

**Comment by deep011** [comment]
c++客户端是？

**Comment by zzs625005** [comment]
我用的是你的c++支持redis-cluster的client，redisClusterContext *rds_ctx = redisClusterConnect(_rdsConnection, HIRCLUSTER_FLAG_NULL); rds_reply = (redisReply *)redisClusterCommand(rds_ctx, "GET %s", key.c_str());这个。在连接一个集群时，发现集群中一个节点的cpu占用率特别高，其他节点cpu占用率很低。

**Comment by zzs625005** [comment]
我用的是你的c++支持redis-cluster的client，redisClusterContext *rds_ctx = redisClusterConnect(_rdsConnection, HIRCLUSTER_FLAG_NULL); rds_reply = (redisReply *)redisClusterCommand(rds_ctx, "GET %s", key.c_str());这个。在连接一个集群时，发现集群中一个节点的cpu占用率特别高，其他节点cpu占用率很低，这样，redis-cluster由于cpu瓶颈不能实现水平扩展了，不知道是client的原因还是redis-cluster本身的机制问题。

**Comment by deep011** [comment]
明显是hotkey问题
