### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by splitice** [vipshop/hiredis-vip#4]
After spending quite a while trying to trace a parse error it has come to my attention that it would be really nice to be able to see the state of the parser when the error occurred.

In order to do this I had to break out GDB.

Even if its just the state and current position (token position), this could be extremely useful.

**Comment by deep011** [comment]
Hi, thanks for your advice. I had added the info for command parse failed. See the last commit.

**Comment by splitice** [comment]
Awesome,

And thank you for your hard work in developing this.
