### ISSUE TITLE
Deleting Multiple Keys

### ISSUE THREAD

**Issue by nginxsantos** [vipshop/hiredis-vip#42]
How can I delete Multiple keys in a single command. The following syntax does not work. I am guessing cluster does not support when the keys are distributed across the slots!!
 
The following didn't work!!

redisClusterAsyncCommand(redisCtxt, redisDeleteCallback, trans, "DEL %s %s %s %s", k1, k2, k3,k4)

**Comment by deep011** [comment]
Asynchronous API now not support multi-key command
