### ISSUE TITLE
build不过，出现对......未定义引用

### ISSUE THREAD

**Issue by SixHe1412** [vipshop/hiredis-vip#44]
/opt/workspace/connRedis/Debug/../test.cpp:15：对‘redisClusterConnect’未定义的引用
/opt/workspace/connRedis/Debug/../test.cpp:24：对‘redisClusterCommand’未定义的引用
/opt/workspace/connRedis/Debug/../test.cpp:28：对‘redisClusterFree’未定义的引用
/opt/workspace/connRedis/Debug/../test.cpp:32：对‘freeReplyObject’未定义的引用
/opt/workspace/connRedis/Debug/../test.cpp:35：对‘redisClusterCommand’未定义的引用
/opt/workspace/connRedis/Debug/../test.cpp:38：对‘redisClusterFree’未定义的引用
/opt/workspace/connRedis/Debug/../test.cpp:42：对‘freeReplyObject’未定义的引用
/opt/workspace/connRedis/Debug/../test.cpp:45：对‘redisClusterFree’未定义的引用

这情况是怎么一回事牙？

**Comment by SixHe1412** [comment]
这个库文件是libhiredis_vip.a、libhiredis_vip.so么？为何加入搜索路径还是会出现上面的情况？

**Comment by deep011** [comment]
你安装到哪里了

**Comment by SixHe1412** [comment]
我在linux上的eclipse for C++编译的，make和make install后生成了libhiredis.so和~.a，放在/usr/local/lib下。。。

**Comment by deep011** [comment]
你在 /etc/ld.so.conf.d/ 目录下增加/usr/local/lib目录试试
