### ISSUE TITLE
有没有测试文档呀，多谢

### ISSUE THREAD

**Issue by Layamon** [vipshop/hiredis-vip#45]

**Comment by deep011** [comment]
这里有些简单的说明和例子：https://github.com/vipshop/hiredis-vip/wiki

**Comment by Layamon** [comment]
嗯嗯，有没有那种性能测试的呀，或者有什么推荐的工具？要么就只能自己写代码测试了 
╯□╰

**Comment by deep011** [comment]
性能方面没有问题，对官方hiredis库几乎没有损耗。

**Comment by Layamon** [comment]
嗷嗷，好的
