### ISSUE TITLE
ctx get by node is null ? 有可能是什么原因

### ISSUE THREAD

**Issue by Layamon** [vipshop/hiredis-vip#48]

**Comment by deep011** [comment]
你看下内存充足吗？

**Comment by Layamon** [comment]
噢噢，虽然是在一台机器上起了8个redis实例，但是里面没存东西，应该是够用的吧

**Comment by deep011** [comment]
客户端所在的机器，内存够吗

**Comment by Layamon** [comment]
内存是够的，现在发现我用redis-3,2配的集群 client可用，redis-4.0配的集群 client不可用。。。是不是客户端还不支持 4.0版本啊

**Comment by deep011** [comment]
你用 HIRCLUSTER_FLAG_ROUTE_USE_SLOTS 这个flag

**Comment by Layamon** [comment]
还是不行啊：请问我的用法对吗？
redisClusterConnect("127.0.0.1:30001,127.0.0.1:30002,127.0.0.1:30003,127.0.0.1:30004,127.0.0.1:30005,127.0.0.1:30006",HIRCLUSTER_FLAG_ROUTE_USE_SLOTS);
 redisReply *reply = redisClusterCommand(cc, "hmget %s %s", key, field);

**Comment by Layamon** [comment]
可以了，谢谢

**Comment by ghost** [comment]
> 可以了，谢谢

你好，请问是通过添加HIRCLUSTER_FLAG_ROUTE_USE_SLOTS来解决的吗？我这里通过在redisClusterConnect中添加了该flag并没有解决错误。
环境：centos6.9（防火墙已关闭，保护模式已关闭），redis4.0.14,
内存情况
```
               total       used       free     shared    buffers     cached
Mem:           31G       4.1G        27G       248K       303M       2.5G
-/+ buffers/cache:       1.3G        30G
Swap:          15G         0B        15G
```
**请问这种错误导致的原因是什么？该如何解决？**

**Comment by peiyuanzheng** [comment]
我这边遇到相同的问题，添加 HIRCLUSTER_FLAG_ROUTE_USE_SLOTS 可以解决。
