### ISSUE TITLE
Lua脚本的支持

### ISSUE THREAD

**Issue by StelleSand** [vipshop/hiredis-vip#51]
你好，我使用hiredis-vip进行Lua脚本的执行的时候，发现即使使用{}保证键在一个slot内，也会出现lua脚本的异常，但是直接在终端上执行就没有问题，请问后面会考虑添加对Lua脚本的一些有限支持吗？

**Comment by GooglerLi** [comment]
具体什么错误呢？可以发出来看下嘛

**Comment by StelleSand** [comment]
17年的问题了，已经不在前前司了，哈哈哈哈~
