### ISSUE TITLE
Unable to use this for redis4.0.1

### ISSUE THREAD

**Issue by nginxsantos** [vipshop/hiredis-vip#58]
I am unable to use this client for the latest redis-stable version redis4.0.1. Although previous stable version 3.2.8 works fine.

Thanks, Santos

**Comment by deep011** [comment]
Please use the HIRCLUSTER_FLAG_ROUTE_USE_SLOTS flag to connect to redis cluster.

**Comment by nginxsantos** [comment]
Any plans of a new patch?

**Comment by deep011** [comment]
Yes, in the near future！

**Comment by nginxsantos** [comment]
Do you have a time line when the client can be upgraded for redis 4.0?
