### ISSUE TITLE
你好，关于redis-cluster-c-client的一个问题

### ISSUE THREAD

**Issue by zzs625005** [vipshop/hiredis-vip#6]
我们存储的value是若干个struct的内存字节拷贝，然后转换为字符串。我遇到了一个问题，当字符串中某个byte是0时，value会被截断，看了代码，应该是redisvFormatCommand这个函数中是已'\0'判断字符串结束的，如下：while(*c != '\0')。我想请问作者，这个可以改成传入字符串字节长度，代替'\0'标记结束吗？ 因为我发现网上一些其他的主从client是可以支持包含'\0'字节的value设置的。
谢谢！

**Comment by deep011** [comment]
你好！
我增加了redisClusterCommandArgv()，redisClusterAppendCommandArgv()，redisClusterAsyncCommandArgv()这三个函数，可以使得key和value中包含'\0'等特殊字符。

**Comment by zzs625005** [comment]
你好，非常感谢。
我尝试用redisClusterCommandArgv方式执行hset和hget操作。在执行hset时，确实\0,\t这些之前不支持的字符可以作为value值顺利存入。但是在执行hget时，获取到的结果中reply->str和reply->len不匹配（如reply->str长度为1，但是reply->len是4，即reply->str不能获取完整的字符串值）。
请再帮忙修复一下吧。
万分感谢！

**Comment by deep011** [comment]
你好，reply->str的长度不能以strlen()获取（因为其中可能包含'\0'），而是以reply->len为准。
你只需获取reply->str中的reply->len长度字符串即可。

**Comment by zzs625005** [comment]
你好！
我这测试的结果是，通过reply->str和reply->len不能获取原字符串。
例如:strlen(reply->str)=1,reply->len=4，我去获取以reply->str为首地址的4个byte，只有第一个byte数据和我存入的一样，其他的数据都被修改过。麻烦再看下什么原因。谢谢！

**Comment by deep011** [comment]
我这边测试没有你说的这个问题。你是怎么比较然后看出来字符串被修改过的？可否提供下测试使用的key，value

**Comment by deep011** [comment]
@zzs625005 你也可以把你的key和value放入这个redis cluster集群：114.215.134.246:34521

**Comment by zzs625005** [comment]
你好，能发下你的邮箱吗？我把测试用例和复现过程给你。我的环境连不上你的集群。
谢谢！

**Comment by deep011** [comment]
加我qq吧：1005492787

**Comment by deep011** [comment]
Problem is solved。Close it.
