### ISSUE TITLE
Synchronous operations with redisClusterAsyncContext

### ISSUE THREAD

**Issue by badarihp** [vipshop/hiredis-vip#67]
Hi,
  For my use case I have opted to connected to redisdb with cluster async mode. For one of the use case I would like to do some synchronous operations, but i do not wish to connect in sync mode to redis db. 
I have handle to redisClusterAsyncContext, and when i try to execute redis cluster function to get reply synchronously the command fails.

    redisClusterAsyncCommand(c, getCallback, &count, "SET key1 test1");
    printf("Set the key \n");
....
...
after some point, by this time the key is set in redis db.... 

    redisReply* reply = redisClusterCommand(c->cc, "GET key1");
    if(reply)
    {
        printf("GET: %s\n", reply->str);
        freeReplyObject(reply);
    }
    else
        printf("redisReply is null\n");

with the above code redisReply object is always NULL. 

I would like to know if we can do some synchronous operations using redisClusterAsyncContext ?

**Comment by deep011** [comment]
Synchronous operations can't use the redisClusterAsyncContext.

**Comment by badarihp** [comment]
ok Thank you for the info.
