### ISSUE TITLE
请问支持普通复制场景下的事务吗？

### ISSUE THREAD

**Issue by lxyscls** [vipshop/hiredis-vip#69]
1 master，N slaves，M sentinels，读写均在master上进行，sentinel帮忙做故障转移。

请问几个问题

- 是否支持multi/exec/watch等事务操作？

- 如果支持，redisClusterSetOptionAddNodes中需要把sentinel的addrs也加上吗？

- 只有1个master，也必须开启cluster功能？

期待回复，谢谢！

**Comment by GooglerLi** [comment]
是否支持multi/exec/watch等事务操作？

不支持上述命令的，具体可以看下command.c文件里面支持的命令
