### ISSUE TITLE
How to connect to multiple redis-servers in a cluster?

### ISSUE THREAD

**Issue by zhang2ding** [vipshop/hiredis-vip#7]
I have a cluster including three masters and three slaves. 
How to connect to all the masters in one context?

**Comment by deep011** [comment]
hi zhang2ding
You just provide one redis address(ip:port), hiredis-vip will send the command to a correct redis in the cluster.
See some examples: https://github.com/vipshop/hiredis-vip/wiki

**Comment by zhang2ding** [comment]
Thanks.I think that you should put these samples in the source code, i.e. https://github.com/vipshop/hiredis-vip/tree/master/examples.

**Comment by deep011** [comment]
Yes, i will do it later.
