### ISSUE TITLE
使用该client的异步 api，发出的请求和对应的结果是fifo模型么

### ISSUE THREAD

**Issue by achilsh** [vipshop/hiredis-vip#77]
在使用该client 的异步API 连接 redis 集群，每次请求和对应的回应是fifo.还是回报不保证有序。因为在长连接上，请求没有携带 seq, 如果不保持有序的话，长连接上数据就全乱了。所以向你们确定这种场景

**Comment by deep011** [comment]
是的

**Comment by achilsh** [comment]
收到，hiredis-vip设计异步模式时应该能保证有序

**Comment by achilsh** [comment]
check it as describled
